---
sudo: required
dist: trusty
language: node_js
node_js:
  - '4.4'
install:
  - sudo add-apt-repository -y ppa:git-core/ppa
  - sudo apt-get update
  - sudo apt-get install -y git
  - npm install
after_script:
  - npm run coveralls
